using System;
using System.Globalization;
using System.IO;

namespace CADImporter.Editor
{
    /// <summary>
    /// Converts IFC (BIM) files into per-element STL meshes plus an assembly manifest, using the
    /// IfcOpenShell library bundled with FreeCAD (driven through FreeCADCmd's Python). IFC geometry
    /// is tessellated in each element's own local frame and the spatial/aggregation tree
    /// (project → site → building → storey → element) is preserved with per-element pivots and
    /// surface colours, so a building imports as a navigable hierarchy rather than a flat soup.
    /// </summary>
    public static class IfcConverter
    {
        /// <summary>
        /// Tessellates <paramref name="sourceFile"/> into numbered STL files plus a manifest.json in
        /// <paramref name="outputDir"/>. All geometry and placements are emitted in metres.
        /// <paramref name="linearDeflectionMeters"/> is the tessellation chord tolerance.
        /// </summary>
        public static bool ConvertToStl(string converterExe, string sourceFile, string outputDir,
            float linearDeflectionMeters, int timeoutSeconds, string label, out string error)
        {
            error = null;
            Directory.CreateDirectory(outputDir);
            string scriptPath = Path.Combine(outputDir, "_ifc.py");
            File.WriteAllText(scriptPath, BuildScript(sourceFile, outputDir, linearDeflectionMeters));

            if (!StepConverter.RunFreeCadScript(converterExe, scriptPath, timeoutSeconds, label, out _, out error))
                return false;

            if (!File.Exists(Path.Combine(outputDir, "manifest.json")))
            {
                error = "IfcOpenShell reported success but produced no manifest (empty or geometry-less model?).";
                return false;
            }
            return true;
        }

        static string BuildScript(string src, string outDir, float linearDeflectionMeters)
        {
            var inv = CultureInfo.InvariantCulture;
            string lin = Math.Max(linearDeflectionMeters, 0.0001f).ToString(inv);

            // Python string literals use single quotes so this C# verbatim string only has to
            // double curly braces ({{ }}); path/marker/number values are interpolated.
            return $@"# Auto-generated by Unity CAD Importer (IFC via IfcOpenShell)
import os, sys, json, struct, math, traceback
import numpy as np
import ifcopenshell
import ifcopenshell.geom
import ifcopenshell.util.placement as PL
import ifcopenshell.util.unit as UU
import ifcopenshell.util.element as UE

SRC = r'''{src}'''
OUT = r'''{outDir}'''
LIN = {lin}

def prog(frac, m):
    print('{StepConverter.ProgressMarker} %.4f %s' % (frac, m), flush=True)

def write_stl(path, verts, faces):
    with open(path, 'wb') as fp:
        fp.write(b'\0' * 80)
        fp.write(struct.pack('<I', len(faces)))
        for a, b, c in faces:
            va, vb, vc = verts[a], verts[b], verts[c]
            ux, uy, uz = vb[0]-va[0], vb[1]-va[1], vb[2]-va[2]
            wx, wy, wz = vc[0]-va[0], vc[1]-va[1], vc[2]-va[2]
            nx, ny, nz = uy*wz-uz*wy, uz*wx-ux*wz, ux*wy-uy*wx
            l = math.sqrt(nx*nx+ny*ny+nz*nz) or 1.0
            fp.write(struct.pack('<12fH', nx/l, ny/l, nz/l,
                                 va[0], va[1], va[2], vb[0], vb[1], vb[2],
                                 vc[0], vc[1], vc[2], 0))

def mat_to_pos_quat(M):
    # M: 4x4 rigid transform (metres) -> position + quaternion (x,y,z,w).
    p = [float(M[0][3]), float(M[1][3]), float(M[2][3])]
    r = np.array(M)[:3, :3]
    t = r[0][0] + r[1][1] + r[2][2]
    if t > 0:
        s = math.sqrt(t + 1.0) * 2
        w = 0.25 * s
        x = (r[2][1]-r[1][2]) / s; y = (r[0][2]-r[2][0]) / s; z = (r[1][0]-r[0][1]) / s
    elif r[0][0] > r[1][1] and r[0][0] > r[2][2]:
        s = math.sqrt(1.0 + r[0][0] - r[1][1] - r[2][2]) * 2
        w = (r[2][1]-r[1][2]) / s; x = 0.25 * s; y = (r[0][1]+r[1][0]) / s; z = (r[0][2]+r[2][0]) / s
    elif r[1][1] > r[2][2]:
        s = math.sqrt(1.0 + r[1][1] - r[0][0] - r[2][2]) * 2
        w = (r[0][2]-r[2][0]) / s; x = (r[0][1]+r[1][0]) / s; y = 0.25 * s; z = (r[1][2]+r[2][1]) / s
    else:
        s = math.sqrt(1.0 + r[2][2] - r[0][0] - r[1][1]) * 2
        w = (r[1][0]-r[0][1]) / s; x = (r[0][2]+r[2][0]) / s; y = (r[1][2]+r[2][1]) / s; z = 0.25 * s
    return p, [float(x), float(y), float(z), float(w)]

def color_of(geo):
    try:
        mats = geo.materials
        if not mats:
            return None
        m = mats[0]
        try:
            mids = [i for i in geo.material_ids if 0 <= i < len(mats)]
            if mids:
                counts = {{}}
                for i in mids:
                    counts[i] = counts.get(i, 0) + 1
                m = mats[max(counts, key=counts.get)]
        except Exception:
            pass
        d = m.diffuse
        r, g, b = float(d.r()), float(d.g()), float(d.b())
        if any(v != v or v < 0 for v in (r, g, b)):
            return None
        a = 1.0
        try:
            if m.has_transparency():
                tr = float(m.transparency)
                if tr == tr:
                    a = 1.0 - tr
        except Exception:
            pass
        return [r, g, b, a]
    except Exception:
        return None

def material_hint(elem):
    # Lower-cased IFC material name(s) + category, so the importer can colour by material
    # (glass -> translucent, steel -> metallic, ...) even when the type is generic.
    try:
        parts = []
        for mm in UE.get_materials(elem) or ():
            nm = getattr(mm, 'Name', None)
            if nm:
                parts.append(nm)
            cat = getattr(mm, 'Category', None)
            if cat:
                parts.append(cat)
        return ' '.join(parts).lower() if parts else None
    except Exception:
        return None

def main():
    os.makedirs(OUT, exist_ok=True)
    prog(0.02, 'opening IFC...')
    f = ifcopenshell.open(SRC)
    unit_scale = UU.calculate_unit_scale(f)

    settings = ifcopenshell.geom.settings()
    settings.set('use-world-coords', False)
    settings.set('weld-vertices', True)
    # Off: unstyled elements report no material, so the importer can colour them by IFC category
    # (the professional default palette) instead of a flat IfcOpenShell grey. Authored styles win.
    settings.set('apply-default-materials', False)
    try:
        settings.set('mesher-linear-deflection', LIN)
    except Exception:
        pass

    tess = {{}}
    prog(0.05, 'tessellating geometry (this can take a while on large buildings)...')
    it = ifcopenshell.geom.iterator(settings, f, max(1, os.cpu_count() or 1))
    if it.initialize():
        n = 0
        while True:
            shp = it.get()
            geo = shp.geometry
            faces = np.array(geo.faces, dtype=int).reshape(-1, 3)
            if len(faces):
                verts = np.array(geo.verts, dtype=float).reshape(-1, 3)
                tess[shp.id] = (verts.tolist(), faces.tolist(), color_of(geo))
            n += 1
            if n % 25 == 0:
                pct = it.progress()  # 0..100 across the whole model
                prog(0.05 + 0.77 * (pct / 100.0), 'tessellating geometry %d%%...' % pct)
            if not it.next():
                break
    prog(0.82, 'tessellated %d product(s) with geometry' % len(tess))

    counter = [0]

    def world_matrix(elem):
        pl = getattr(elem, 'ObjectPlacement', None)
        if pl is None:
            return np.eye(4)
        M = np.array(PL.get_local_placement(pl), dtype=float)
        M[:3, 3] *= unit_scale
        return M

    def children_of(elem):
        kids = []
        for rel in getattr(elem, 'IsDecomposedBy', None) or []:
            kids += list(rel.RelatedObjects)
        for rel in getattr(elem, 'ContainsElements', None) or []:
            kids += list(rel.RelatedElements)
        return kids

    def build(elem, parent_world):
        W = world_matrix(elem)
        local = np.linalg.inv(parent_world) @ W
        pos, quat = mat_to_pos_quat(local)
        name = getattr(elem, 'Name', None) or elem.is_a()
        node = {{'name': name, 'ifcType': elem.is_a(), 'pos': pos, 'quat': quat, 'mesh': -1, 'children': []}}
        rec = tess.get(elem.id())
        if rec is not None:
            verts, faces, color = rec
            idx = counter[0]
            write_stl(os.path.join(OUT, '%03d.stl' % idx), verts, faces)
            counter[0] += 1
            node['mesh'] = idx
            if color is not None:
                node['color'] = color
            mh = material_hint(elem)
            if mh:
                node['material'] = mh
            if counter[0] % 50 == 0:
                prog(0.82 + 0.16 * (counter[0] / max(len(tess), 1)),
                     'placing part %d/%d...' % (counter[0], len(tess)))
        for c in children_of(elem):
            cn = build(c, W)
            if cn is not None:
                node['children'].append(cn)
        if node['mesh'] < 0 and not node['children']:
            return None
        return node

    roots = []
    for proj in f.by_type('IfcProject'):
        node = build(proj, np.eye(4))
        if node is not None:
            roots.append(node)

    if not roots:
        # No usable spatial tree: emit every geometric product at the origin.
        prog(0.9, 'no spatial tree; emitting products flat...')
        for pid, rec in tess.items():
            verts, faces, color = rec
            idx = counter[0]
            write_stl(os.path.join(OUT, '%03d.stl' % idx), verts, faces)
            counter[0] += 1
            prod = f.by_id(pid)
            node = {{'name': (getattr(prod, 'Name', None) or ('Product_%d' % pid)),
                     'ifcType': prod.is_a(), 'pos': [0, 0, 0], 'quat': [0, 0, 0, 1],
                     'mesh': idx, 'children': []}}
            if color is not None:
                node['color'] = color
            roots.append(node)

    manifest = {{'unit': 'm', 'worldBBox': None, 'nodes': roots}}
    with open(os.path.join(OUT, 'manifest.json'), 'w') as mf:
        json.dump(manifest, mf)
    prog(1.0, 'done: %d mesh part(s)' % counter[0])
    print('{StepConverter.OkMarker} %d' % counter[0])

try:
    main()
except Exception:
    traceback.print_exc()
    sys.exit(1)
";
        }
    }
}
